# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
from .database import run_query

# Dicionário de traduções v14.1 - SUPORTE TOTAL MULTI-IDIOMA
TRANSLATIONS = {
    'pt': {
        # Gerais
        'bal': 'Meu Saldo',
        'logout': 'Sair',
        'refresh': 'Atualizar',
        'lang_sel': 'Idioma',
        'status': 'Status',
        'value': 'Valor',
        'reason': 'Motivo',
        'confirm': 'Confirmar',
        'cancel': 'Cancelar',
        'execute': 'Executar',
        'loading': 'Carregando...',
        'change_pass': '🔒 Alterar Senha',
        'password': 'Senha',
        'new_pass': '🔑 Nova Senha',
        'pass_changed': 'Senha alterada com sucesso!',
        
        # Admin - Cabeçalhos
        'cmd_header': 'COMANDO RIPARITECH',
        'family_bal': '💰 Monitoramento de Ativos',
        'panel': '🔎 Tarefas',
        'cashier': '💸 Lançamentos',
        'mgmt': '⚙️ Usuários',
        'allowance_tab': '📅 Mesada',
        
        # Admin - Tarefas
        'tab_approvals': 'Aprovações',
        'tab_followup': 'Acompanhar',
        'tab_new_mission': 'Nova Missão',
        'validate_delivery': 'Validar Entregas',
        'audit_title': 'Auditoria de Prazos e Status',
        'no_pending': 'Nenhuma entrega aguardando aprovação.',
        'pay_btn': 'Pagar',
        'reopen_btn': 'Reabrir Missão',
        'overdue_warn': '⚠️ ATRASO DETECTADO',
        'late_delivery_warn': '⌛ ENTREGUE COM ATRASO',
        'on_time': 'No prazo ✅',
        'apply_fine': 'Aplicar Multa',
        'conf_fine_btn': 'Confirmar Multa',
        'fine_applied_toast': 'Punição financeira aplicada!',
        'cancel_btn': '🚫 Cancelar',
        'col_responsible': 'Responsável',
        'col_task': 'Tarefa',
        'col_completion': 'Conclusão',
        'col_actions': 'Ações',
        'status_open': 'ABERTO',
        'status_pending': 'PENDENTE',
        'status_paid': 'PAGO',
        'status_canceled': 'CANCELADO',
        'status_failed': 'FALHOU',
        'btn_fine': '💸 Multar',
        
        # Admin - Mesada
        'allowance_title': 'Configuração de Mesada',
        'day_of_month': 'Dia do Pagamento (1-28)',
        'allowance_desc': 'Mesada Automática',
        'frequency': 'Frequência',
        'freq_monthly': 'Mensal',
        'freq_weekly': 'Semanal',
        'freq_daily': 'Diária',
        'day_of_week': 'Dia da Semana',
        'weekdays': ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo'],
        
        # Admin - Lançamentos e Usuários
        'manual_adjust': 'Ajuste de Saldo Manual',
        'target_acc': 'Escolher Conta',
        'op_type': 'Tipo de Operação',
        'deposit': 'Depósito',
        'withdraw': 'Retirada',
        'active_users': 'Usuários Ativos',
        'new_user': 'Novo Usuário',
        'delete_acc': 'Excluir Conta',
        
        # Kids - Abas
        'home': 'Extrato e Histórico',
        'missions': 'Missões',
        'transfer': 'Transferir',
        'tools': 'Câmbio',
        
        # Kids - Funcionalidades
        'last_mov': 'Últimas Movimentações',
        'no_mov': 'Nenhum registro de movimentação encontrado.',
        'active_missions': 'Missões Ativas',
        'deadline': 'Prazo',
        'no_deadline': 'Sem prazo definido',
        'mark_done': 'MARCAR COMO CONCLUÍDO',
        'sent_approval': 'Missão enviada para aprovação do Comando! 🚀',
        'no_active_miss': 'Tudo pronto! Você não tem missões pendentes.',
        'send_money': 'Enviar Dinheiro',
        'to_whom': 'Destinatário',
        'how_much': 'Quanto?',
        'send_now': 'ENVIAR AGORA 💸',
        'insufficient': 'Saldo insuficiente.',
        'transfer_done': 'Transferência realizada com sucesso!',
        'profile_tab': 'Avatar',
        'theme_select': '🎨 Tema da Interface',
        'theme_changed': 'Tema atualizado!',
        'fx_title': 'Conversão de Patrimônio',
        'next_allowance': 'Próxima Mesada',
        'avatar_builder': 'Monte seu Avatar',
        'face': 'Rosto',
        'hair': 'Cabelo',
        'clothes': 'Roupa',
        'save_avatar': 'Salvar Avatar',
        'bg_image_label': 'Imagem de Fundo (Upload)',
        'bg_image_placeholder': 'Faça o upload de uma imagem...',
        'bg_updated': 'Fundo atualizado!',
        'remove_bg': 'Remover Fundo',
        'bg_removed': 'Fundo removido!',
    },
    'en': {
        'bal': 'My Balance',
        'logout': 'Logout',
        'refresh': 'Refresh',
        'lang_sel': 'Language',
        'status': 'Status',
        'value': 'Amount',
        'reason': 'Reason',
        'confirm': 'Confirm',
        'cancel': 'Cancel',
        'execute': 'Execute',
        'loading': 'Loading...',
        'change_pass': '🔒 Change Password',
        'password': 'Password',
        'new_pass': '🔑 New Password',
        'pass_changed': 'Password changed successfully!',
        'cmd_header': 'RIPARITECH COMMAND',
        'family_bal': '💰 Asset Monitoring',
        'panel': '🔎 Tasks',
        'cashier': '💸 Entries',
        'mgmt': '⚙️ Users',
        'allowance_tab': '📅 Allowance',
        'tab_approvals': 'Approvals',
        'tab_followup': 'Follow-up',
        'tab_new_mission': 'New Mission',
        'validate_delivery': 'Validate Deliveries',
        'audit_title': 'Deadline & Status Audit',
        'no_pending': 'No deliveries waiting for approval.',
        'pay_btn': 'Pay',
        'reopen_btn': 'Reopen Task',
        'overdue_warn': '⚠️ OVERDUE DETECTED',
        'late_delivery_warn': '⌛ LATE DELIVERY',
        'on_time': 'On time ✅',
        'apply_fine': 'Apply Fine',
        'conf_fine_btn': 'Confirm Fine',
        'fine_applied_toast': 'Financial penalty applied!',
        'cancel_btn': '🚫 Cancel',
        'col_responsible': 'Responsible',
        'col_task': 'Task',
        'col_completion': 'Completion',
        'col_actions': 'Actions',
        'status_open': 'OPEN',
        'status_pending': 'PENDING',
        'status_paid': 'PAID',
        'status_canceled': 'CANCELED',
        'status_failed': 'FAILED',
        'btn_fine': '💸 Fine',
        'allowance_title': 'Allowance Setup',
        'day_of_month': 'Payment Day (1-28)',
        'allowance_desc': 'Automatic Allowance',
        'frequency': 'Frequency',
        'freq_monthly': 'Monthly',
        'freq_weekly': 'Weekly',
        'freq_daily': 'Daily',
        'day_of_week': 'Day of Week',
        'weekdays': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        'manual_adjust': 'Manual Balance Adjustment',
        'target_acc': 'Select Account',
        'op_type': 'Operation Type',
        'deposit': 'Deposit',
        'withdraw': 'Withdrawal',
        'active_users': 'Active Users',
        'new_user': 'New User',
        'delete_acc': 'Delete Account',
        'home': 'History',
        'missions': 'Missions',
        'transfer': 'Transfer',
        'tools': 'Exchange',
        'last_mov': 'Recent Transactions',
        'no_mov': 'No transactions found.',
        'active_missions': 'Active Missions',
        'deadline': 'Deadline',
        'no_deadline': 'No deadline set',
        'mark_done': 'MARK AS DONE',
        'sent_approval': 'Mission sent for Command approval! 🚀',
        'no_active_miss': 'All clear! No pending missions.',
        'send_money': 'Send Money',
        'to_whom': 'Recipient',
        'how_much': 'Amount?',
        'send_now': 'SEND NOW 💸',
        'insufficient': 'Insufficient balance.',
        'transfer_done': 'Transfer completed successfully!',
        'profile_tab': 'Avatar',
        'theme_select': '🎨 Interface Theme',
        'theme_changed': 'Theme updated!',
        'fx_title': 'Wealth Conversion',
        'next_allowance': 'Next Allowance',
        'avatar_builder': 'Build your Avatar',
        'face': 'Face',
        'hair': 'Hair',
        'clothes': 'Clothes',
        'save_avatar': 'Save Avatar',
        'bg_image_label': 'Background Image (Upload)',
        'bg_image_placeholder': 'Upload an image...',
        'bg_updated': 'Background updated!',
        'remove_bg': 'Remove Background',
        'bg_removed': 'Background removed!',
    },
    'es': {
        'bal': 'Mi Saldo',
        'logout': 'Salir',
        'refresh': 'Actualizar',
        'lang_sel': 'Idioma',
        'status': 'Estado',
        'value': 'Valor',
        'reason': 'Motivo',
        'confirm': 'Confirmar',
        'cancel': 'Cancelar',
        'execute': 'Ejecutar',
        'loading': 'Cargando...',
        'change_pass': '🔒 Cambiar Contraseña',
        'password': 'Contraseña',
        'new_pass': '🔑 Nueva Contraseña',
        'pass_changed': '¡Contraseña cambiada con éxito!',
        'cmd_header': 'COMANDO RIPARITECH',
        'family_bal': '💰 Monitoreo de Activos',
        'panel': '🔎 Tareas',
        'cashier': '💸 Movimientos',
        'mgmt': '⚙️ Usuarios',
        'allowance_tab': '📅 Mesada',
        'tab_approvals': 'Aprobaciones',
        'tab_followup': 'Seguimiento',
        'tab_new_mission': 'Nueva Misión',
        'validate_delivery': 'Validar Entregas',
        'audit_title': 'Auditoría de Plazos y Estado',
        'no_pending': 'No hay entregas pendientes.',
        'pay_btn': 'Pagar',
        'reopen_btn': 'Reabrir Tarea',
        'overdue_warn': '⚠️ ATRASO DETECTADO',
        'late_delivery_warn': '⌛ ENTREGADO CON ATRASO',
        'on_time': 'A tiempo ✅',
        'apply_fine': 'Aplicar Multa',
        'conf_fine_btn': 'Confirmar Multa',
        'fine_applied_toast': '¡Penalización aplicada!',
        'cancel_btn': '🚫 Cancelar',
        'col_responsible': 'Responsable',
        'col_task': 'Tarea',
        'col_completion': 'Conclusión',
        'col_actions': 'Acciones',
        'status_open': 'ABIERTO',
        'status_pending': 'PENDIENTE',
        'status_paid': 'PAGADO',
        'status_canceled': 'CANCELADO',
        'status_failed': 'FALLIDO',
        'btn_fine': '💸 Multar',
        'allowance_title': 'Configuración de Mesada',
        'day_of_month': 'Día de Pago (1-28)',
        'allowance_desc': 'Mesada Automática',
        'frequency': 'Frecuencia',
        'freq_monthly': 'Mensual',
        'freq_weekly': 'Semanal',
        'freq_daily': 'Diaria',
        'day_of_week': 'Día de la Semana',
        'weekdays': ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'],
        'manual_adjust': 'Ajuste Manual de Saldo',
        'target_acc': 'Elegir Cuenta',
        'op_type': 'Tipo de Operación',
        'deposit': 'Depósito',
        'withdraw': 'Retiro',
        'active_users': 'Usuarios Activos',
        'new_user': 'Nuevo Usuario',
        'delete_acc': 'Eliminar Cuenta',
        'home': 'Historial',
        'missions': 'Misiones',
        'transfer': 'Transferir',
        'tools': 'Cambio',
        'last_mov': 'Últimos Movimientos',
        'no_mov': 'No se encontraron movimientos.',
        'active_missions': 'Misiones Activas',
        'deadline': 'Plazo',
        'no_deadline': 'Sin plazo definido',
        'mark_done': 'MARCAR COMO HECHO',
        'sent_approval': '¡Misión enviada para aprobación! 🚀',
        'no_active_miss': '¡Todo listo! No tienes misiones pendientes.',
        'send_money': 'Enviar Dinero',
        'to_whom': 'Destinatario',
        'how_much': '¿Cuánto?',
        'send_now': 'ENVIAR AHORA 💸',
        'insufficient': 'Saldo insuficiente.',
        'transfer_done': '¡Transferencia realizada!',
        'profile_tab': 'Avatar',
        'theme_select': '🎨 Tema de la Interfaz',
        'theme_changed': '¡Tema actualizado!',
        'fx_title': 'Conversión de Patrimonio',
        'next_allowance': 'Próxima Mesada',
        'avatar_builder': 'Crea tu Avatar',
        'face': 'Cara',
        'hair': 'Pelo',
        'clothes': 'Ropa',
        'save_avatar': 'Guardar Avatar',
        'bg_image_label': 'Imagen de Fondo (Subir)',
        'bg_image_placeholder': 'Sube una imagen...',
        'bg_updated': '¡Fondo actualizado!',
        'remove_bg': 'Quitar Fondo',
        'bg_removed': '¡Fondo eliminado!',
    },
    'fr': {
        'bal': 'Mon Solde',
        'logout': 'Déconnexion',
        'refresh': 'Actualiser',
        'lang_sel': 'Langue',
        'status': 'Statut',
        'value': 'Montant',
        'reason': 'Motif',
        'confirm': 'Confirmer',
        'cancel': 'Annuler',
        'execute': 'Exécuter',
        'loading': 'Chargement...',
        'change_pass': '🔒 Changer le mot de passe',
        'password': 'Mot de passe',
        'new_pass': '🔑 Nouveau mot de passe',
        'pass_changed': 'Mot de passe modifié avec succès !',
        'cmd_header': 'COMMANDE RIPARITECH',
        'family_bal': '💰 Suivi des Actifs',
        'panel': '🔎 Tâches',
        'cashier': '💸 Écritures',
        'mgmt': '⚙️ Utilisateurs',
        'allowance_tab': '📅 Argent de poche',
        'tab_approvals': 'Approbations',
        'tab_followup': 'Suivi',
        'tab_new_mission': 'Nouvelle Mission',
        'validate_delivery': 'Valider les livraisons',
        'audit_title': 'Audit des délais et statuts',
        'no_pending': 'Aucune livraison en attente d\'approbation.',
        'pay_btn': 'Payer',
        'reopen_btn': 'Rouvrir la tâche',
        'overdue_warn': '⚠️ RETARD DÉTECTÉ',
        'late_delivery_warn': '⌛ LIVRAISON TARDIVE',
        'on_time': 'À l\'heure ✅',
        'apply_fine': 'Appliquer une amende',
        'conf_fine_btn': 'Confirmer l\'amende',
        'fine_applied_toast': 'Pénalité financière appliquée !',
        'cancel_btn': '🚫 Annuler',
        'col_responsible': 'Responsable',
        'col_task': 'Tâche',
        'col_completion': 'Achèvement',
        'col_actions': 'Actions',
        'status_open': 'OUVERT',
        'status_pending': 'EN ATTENTE',
        'status_paid': 'PAYÉ',
        'status_canceled': 'ANNULÉ',
        'status_failed': 'ÉCHOUÉ',
        'btn_fine': '💸 Amende',
        'allowance_title': 'Configuration de l\'argent de poche',
        'day_of_month': 'Jour de paiement (1-28)',
        'allowance_desc': 'Argent de poche automatique',
        'frequency': 'Fréquence',
        'freq_monthly': 'Mensuel',
        'freq_weekly': 'Hebdomadaire',
        'freq_daily': 'Quotidien',
        'day_of_week': 'Jour de la semaine',
        'weekdays': ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'],
        'manual_adjust': 'Ajustement manuel du solde',
        'target_acc': 'Sélectionner le compte',
        'op_type': 'Type d\'opération',
        'deposit': 'Dépôt',
        'withdraw': 'Retrait',
        'active_users': 'Utilisateurs actifs',
        'new_user': 'Nouvel utilisateur',
        'delete_acc': 'Supprimer le compte',
        'home': 'Historique',
        'missions': 'Missions',
        'transfer': 'Virement',
        'tools': 'Change',
        'last_mov': 'Transactions récentes',
        'no_mov': 'Aucune transaction trouvée.',
        'active_missions': 'Missions actives',
        'deadline': 'Date limite',
        'no_deadline': 'Pas de date limite',
        'mark_done': 'MARQUER COMME FAIT',
        'sent_approval': 'Mission envoyée pour approbation ! 🚀',
        'no_active_miss': 'Tout est clair ! Pas de missions en attente.',
        'send_money': 'Envoyer de l\'argent',
        'to_whom': 'Destinataire',
        'how_much': 'Combien ?',
        'send_now': 'ENVOYER MAINTENANT 💸',
        'insufficient': 'Solde insuffisant.',
        'transfer_done': 'Virement effectué avec succès !',
        'profile_tab': 'Avatar',
        'theme_select': '🎨 Thème de l\'interface',
        'theme_changed': 'Thème mis à jour !',
        'fx_title': 'Conversion de patrimoine',
        'next_allowance': 'Prochain versement',
        'avatar_builder': 'Créez votre Avatar',
        'face': 'Visage',
        'hair': 'Cheveux',
        'clothes': 'Vêtements',
        'save_avatar': 'Enregistrer l\'Avatar',
        'bg_image_label': 'Image de fond (Télécharger)',
        'bg_image_placeholder': 'Téléchargez une image...',
        'bg_updated': 'Arrière-plan mis à jour !',
        'remove_bg': 'Supprimer l\'arrière-plan',
        'bg_removed': 'Arrière-plan supprimé !',
    },
    'de': {
        'bal': 'Mein Kontostand',
        'logout': 'Abmelden',
        'refresh': 'Aktualisieren',
        'lang_sel': 'Sprache',
        'status': 'Status',
        'value': 'Betrag',
        'reason': 'Grund',
        'confirm': 'Bestätigen',
        'cancel': 'Abbrechen',
        'execute': 'Ausführen',
        'loading': 'Laden...',
        'change_pass': '🔒 Passwort ändern',
        'password': 'Passwort',
        'new_pass': '🔑 Neues Passwort',
        'pass_changed': 'Passwort erfolgreich geändert!',
        'cmd_header': 'RIPARITECH KOMMANDO',
        'family_bal': '💰 Vermögensüberwachung',
        'panel': '🔎 Aufgaben',
        'cashier': '💸 Buchungen',
        'mgmt': '⚙️ Benutzer',
        'allowance_tab': '📅 Taschengeld',
        'tab_approvals': 'Genehmigungen',
        'tab_followup': 'Nachverfolgung',
        'tab_new_mission': 'Neue Mission',
        'validate_delivery': 'Lieferungen validieren',
        'audit_title': 'Fristen- & Statusprüfung',
        'no_pending': 'Keine Lieferungen warten auf Genehmigung.',
        'pay_btn': 'Bezahlen',
        'reopen_btn': 'Aufgabe wiedereröffnen',
        'overdue_warn': '⚠️ VERZUG ERKANNT',
        'late_delivery_warn': '⌛ VERSPÄTETE LIEFERUNG',
        'on_time': 'Pünktlich ✅',
        'apply_fine': 'Strafe verhängen',
        'conf_fine_btn': 'Strafe bestätigen',
        'fine_applied_toast': 'Geldstrafe angewendet!',
        'cancel_btn': '🚫 Abbrechen',
        'col_responsible': 'Verantwortlich',
        'col_task': 'Aufgabe',
        'col_completion': 'Abschluss',
        'col_actions': 'Aktionen',
        'status_open': 'OFFEN',
        'status_pending': 'AUSSTEHEND',
        'status_paid': 'BEZAHLT',
        'status_canceled': 'ABGEBROCHEN',
        'status_failed': 'FEHLGESCHLAGEN',
        'btn_fine': '💸 Strafe',
        'allowance_title': 'Taschengeld-Einstellung',
        'day_of_month': 'Zahltag (1-28)',
        'allowance_desc': 'Automatisches Taschengeld',
        'frequency': 'Häufigkeit',
        'freq_monthly': 'Monatlich',
        'freq_weekly': 'Wöchentlich',
        'freq_daily': 'Täglich',
        'day_of_week': 'Wochentag',
        'weekdays': ['Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag', 'Sonntag'],
        'manual_adjust': 'Manuelle Saldoanpassung',
        'target_acc': 'Konto auswählen',
        'op_type': 'Vorgangsart',
        'deposit': 'Einzahlung',
        'withdraw': 'Auszahlung',
        'active_users': 'Aktive Benutzer',
        'new_user': 'Neuer Benutzer',
        'delete_acc': 'Konto löschen',
        'home': 'Verlauf',
        'missions': 'Missionen',
        'transfer': 'Überweisen',
        'tools': 'Wechselkurs',
        'last_mov': 'Letzte Transaktionen',
        'no_mov': 'Keine Transaktionen gefunden.',
        'active_missions': 'Aktive Missionen',
        'deadline': 'Frist',
        'no_deadline': 'Keine Frist gesetzt',
        'mark_done': 'ALS ERLEDIGT MARKIEREN',
        'sent_approval': 'Mission zur Genehmigung gesendet! 🚀',
        'no_active_miss': 'Alles erledigt! Keine offenen Missionen.',
        'send_money': 'Geld senden',
        'to_whom': 'Empfänger',
        'how_much': 'Wie viel?',
        'send_now': 'JETZT SENDEN 💸',
        'insufficient': 'Unzureichendes Guthaben.',
        'transfer_done': 'Überweisung erfolgreich abgeschlossen!',
        'profile_tab': 'Avatar',
        'theme_select': '🎨 Interface-Design',
        'theme_changed': 'Design aktualisiert!',
        'fx_title': 'Vermögensumrechnung',
        'next_allowance': 'Nächstes Taschengeld',
        'avatar_builder': 'Erstelle deinen Avatar',
        'face': 'Gesicht',
        'hair': 'Haare',
        'clothes': 'Kleidung',
        'save_avatar': 'Avatar speichern',
        'bg_image_label': 'Hintergrundbild (Hochladen)',
        'bg_image_placeholder': 'Ein Bild hochladen...',
        'bg_updated': 'Hintergrund aktualisiert!',
        'remove_bg': 'Hintergrund entfernen',
        'bg_removed': 'Hintergrund entfernt!',
    },
    'it': {
        'bal': 'Il Mio Saldo',
        'logout': 'Esci',
        'refresh': 'Aggiorna',
        'lang_sel': 'Lingua',
        'status': 'Stato',
        'value': 'Importo',
        'reason': 'Motivo',
        'confirm': 'Conferma',
        'cancel': 'Annulla',
        'execute': 'Esegui',
        'loading': 'Caricamento...',
        'change_pass': '🔒 Cambia Password',
        'password': 'Password',
        'new_pass': '🔑 Nuova Password',
        'pass_changed': 'Password cambiata con successo!',
        'cmd_header': 'COMANDO RIPARITECH',
        'family_bal': '💰 Monitoraggio Attività',
        'panel': '🔎 Compiti',
        'cashier': '💸 Movimenti',
        'mgmt': '⚙️ Utenti',
        'allowance_tab': '📅 Paghetta',
        'tab_approvals': 'Approvazioni',
        'tab_followup': 'Monitoraggio',
        'tab_new_mission': 'Nuova Missione',
        'validate_delivery': 'Convalida Consegne',
        'audit_title': 'Audit Scadenze e Stato',
        'no_pending': 'Nessuna consegna in attesa di approvazione.',
        'pay_btn': 'Paga',
        'reopen_btn': 'Riapri Compito',
        'overdue_warn': '⚠️ RITARDO RILEVATO',
        'late_delivery_warn': '⌛ CONSEGNA IN RITARDO',
        'on_time': 'In orario ✅',
        'apply_fine': 'Applica Multa',
        'conf_fine_btn': 'Conferma Multa',
        'fine_applied_toast': 'Sanzione finanziaria applicata!',
        'cancel_btn': '🚫 Annulla',
        'col_responsible': 'Responsabile',
        'col_task': 'Compito',
        'col_completion': 'Completamento',
        'col_actions': 'Azioni',
        'status_open': 'APERTO',
        'status_pending': 'IN ATTESA',
        'status_paid': 'PAGATO',
        'status_canceled': 'ANNULLATO',
        'status_failed': 'FALLITO',
        'btn_fine': '💸 Multa',
        'allowance_title': 'Impostazione Paghetta',
        'day_of_month': 'Giorno di Pagamento (1-28)',
        'allowance_desc': 'Paghetta Automatica',
        'frequency': 'Frequenza',
        'freq_monthly': 'Mensile',
        'freq_weekly': 'Settimanale',
        'freq_daily': 'Giornaliera',
        'day_of_week': 'Giorno della Settimana',
        'weekdays': ['Lunedì', 'Martedì', 'Mercoledì', 'Giovedì', 'Venerdì', 'Sabato', 'Domenica'],
        'manual_adjust': 'Regolazione Manuale Saldo',
        'target_acc': 'Seleziona Conto',
        'op_type': 'Tipo Operazione',
        'deposit': 'Deposito',
        'withdraw': 'Prelievo',
        'active_users': 'Utenti Attivi',
        'new_user': 'Nuovo Utente',
        'delete_acc': 'Elimina Account',
        'home': 'Cronologia',
        'missions': 'Missioni',
        'transfer': 'Trasferisci',
        'tools': 'Cambio',
        'last_mov': 'Transazioni Recenti',
        'no_mov': 'Nessuna transazione trovata.',
        'active_missions': 'Missioni Attive',
        'deadline': 'Scadenza',
        'no_deadline': 'Nessuna scadenza impostata',
        'mark_done': 'SEGNA COME FATTO',
        'sent_approval': 'Missione inviata per approvazione! 🚀',
        'no_active_miss': 'Tutto libero! Nessuna missione in sospeso.',
        'send_money': 'Invia Denaro',
        'to_whom': 'Destinatario',
        'how_much': 'Quanto?',
        'send_now': 'INVIA ORA 💸',
        'insufficient': 'Saldo insufficiente.',
        'transfer_done': 'Trasferimento completato con successo!',
        'profile_tab': 'Avatar',
        'theme_select': '🎨 Tema Interfaccia',
        'theme_changed': 'Tema aggiornato!',
        'fx_title': 'Conversione Patrimonio',
        'next_allowance': 'Prossima Paghetta',
        'avatar_builder': 'Crea il tuo Avatar',
        'face': 'Viso',
        'hair': 'Capelli',
        'clothes': 'Vestiti',
        'save_avatar': 'Salva Avatar',
        'bg_image_label': 'Immagine di Sfondo (Carica)',
        'bg_image_placeholder': 'Carica un\'immagine...',
        'bg_updated': 'Sfondo aggiornato!',
        'remove_bg': 'Rimuovi Sfondo',
        'bg_removed': 'Sfondo rimosso!',
    },
    'ja': {
        'bal': '残高',
        'logout': 'ログアウト',
        'refresh': '更新',
        'lang_sel': '言語',
        'status': 'ステータス',
        'value': '金額',
        'reason': '理由',
        'confirm': '確認',
        'cancel': 'キャンセル',
        'execute': '実行',
        'loading': '読み込み中...',
        'change_pass': '🔒 パスワード変更',
        'password': 'パスワード',
        'new_pass': '🔑 新しいパスワード',
        'pass_changed': 'パスワードが正常に変更されました！',
        'cmd_header': 'RIPARITECH コマンド',
        'family_bal': '💰 資産監視',
        'panel': '🔎 タスク',
        'cashier': '💸 取引',
        'mgmt': '⚙️ ユーザー',
        'allowance_tab': '📅 お小遣い',
        'tab_approvals': '承認',
        'tab_followup': 'フォローアップ',
        'tab_new_mission': '新しいミッション',
        'validate_delivery': '納品確認',
        'audit_title': '期限とステータスの監査',
        'no_pending': '承認待ちの納品はありません。',
        'pay_btn': '支払う',
        'reopen_btn': 'タスク再開',
        'overdue_warn': '⚠️ 遅延検出',
        'late_delivery_warn': '⌛ 遅延納品',
        'on_time': '時間通り ✅',
        'apply_fine': '罰金を科す',
        'conf_fine_btn': '罰金を確認',
        'fine_applied_toast': '金銭的ペナルティが適用されました！',
        'cancel_btn': '🚫 キャンセル',
        'col_responsible': '担当者',
        'col_task': 'タスク',
        'col_completion': '完了',
        'col_actions': 'アクション',
        'status_open': '未着手',
        'status_pending': '保留中',
        'status_paid': '支払済',
        'status_canceled': 'キャンセル',
        'status_failed': '失敗',
        'btn_fine': '💸 罰金',
        'allowance_title': 'お小遣い設定',
        'day_of_month': '支払日 (1-28)',
        'allowance_desc': '自動お小遣い',
        'frequency': '頻度',
        'freq_monthly': '毎月',
        'freq_weekly': '毎週',
        'freq_daily': '毎日',
        'day_of_week': '曜日',
        'weekdays': ['月曜日', '火曜日', '水曜日', '木曜日', '金曜日', '土曜日', '日曜日'],
        'manual_adjust': '手動残高調整',
        'target_acc': '口座選択',
        'op_type': '操作タイプ',
        'deposit': '預入',
        'withdraw': '引出',
        'active_users': 'アクティブユーザー',
        'new_user': '新規ユーザー',
        'delete_acc': 'アカウント削除',
        'home': '履歴',
        'missions': 'ミッション',
        'transfer': '送金',
        'tools': '両替',
        'last_mov': '最近の取引',
        'no_mov': '取引は見つかりませんでした。',
        'active_missions': 'アクティブなミッション',
        'deadline': '期限',
        'no_deadline': '期限なし',
        'mark_done': '完了としてマーク',
        'sent_approval': 'ミッションが承認のために送信されました！ 🚀',
        'no_active_miss': '完了！ 保留中のミッションはありません。',
        'send_money': '送金する',
        'to_whom': '受取人',
        'how_much': 'いくら？',
        'send_now': '今すぐ送信 💸',
        'insufficient': '残高不足。',
        'transfer_done': '送金が正常に完了しました！',
        'profile_tab': 'アバター',
        'theme_select': '🎨 インターフェーステーマ',
        'theme_changed': 'テーマが更新されました！',
        'fx_title': '資産換算',
        'next_allowance': '次回のお小遣い',
        'avatar_builder': 'アバターを作成',
        'face': '顔',
        'hair': '髪',
        'clothes': '服',
        'save_avatar': 'アバターを保存',
        'bg_image_label': '背景画像 (アップロード)',
        'bg_image_placeholder': '画像をアップロード...',
        'bg_updated': '背景が更新されました！',
        'remove_bg': '背景を削除',
        'bg_removed': '背景が削除されました！',
    },
    'zh': {
        'bal': '我的余额',
        'logout': '登出',
        'refresh': '刷新',
        'lang_sel': '语言',
        'status': '状态',
        'value': '金额',
        'reason': '原因',
        'confirm': '确认',
        'cancel': '取消',
        'execute': '执行',
        'loading': '加载中...',
        'change_pass': '🔒 修改密码',
        'password': '密码',
        'new_pass': '🔑 新密码',
        'pass_changed': '密码修改成功！',
        'cmd_header': 'RIPARITECH 指挥部',
        'family_bal': '💰 资产监控',
        'panel': '🔎 任务',
        'cashier': '💸 账目',
        'mgmt': '⚙️ 用户',
        'allowance_tab': '📅 零花钱',
        'tab_approvals': '审批',
        'tab_followup': '跟进',
        'tab_new_mission': '新任务',
        'validate_delivery': '验证交付',
        'audit_title': '截止日期与状态审计',
        'no_pending': '没有等待审批的交付。',
        'pay_btn': '支付',
        'reopen_btn': '重启任务',
        'overdue_warn': '⚠️ 检测到逾期',
        'late_delivery_warn': '⌛ 延迟交付',
        'on_time': '准时 ✅',
        'apply_fine': '处以罚款',
        'conf_fine_btn': '确认罚款',
        'fine_applied_toast': '已实施经济处罚！',
        'cancel_btn': '🚫 取消',
        'col_responsible': '负责人',
        'col_task': '任务',
        'col_completion': '完成情况',
        'col_actions': '操作',
        'status_open': '开启',
        'status_pending': '待定',
        'status_paid': '已付',
        'status_canceled': '已取消',
        'status_failed': '失败',
        'btn_fine': '💸 罚款',
        'allowance_title': '零花钱设置',
        'day_of_month': '付款日 (1-28)',
        'allowance_desc': '自动零花钱',
        'frequency': '频率',
        'freq_monthly': '每月',
        'freq_weekly': '每周',
        'freq_daily': '每天',
        'day_of_week': '星期',
        'weekdays': ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日'],
        'manual_adjust': '手动余额调整',
        'target_acc': '选择账户',
        'op_type': '操作类型',
        'deposit': '存款',
        'withdraw': '取款',
        'active_users': '活跃用户',
        'new_user': '新用户',
        'delete_acc': '删除账户',
        'home': '历史记录',
        'missions': '任务',
        'transfer': '转账',
        'tools': '汇率',
        'last_mov': '最近交易',
        'no_mov': '未找到交易记录。',
        'active_missions': '进行中的任务',
        'deadline': '截止日期',
        'no_deadline': '未设置截止日期',
        'mark_done': '标记为完成',
        'sent_approval': '任务已发送审批！ 🚀',
        'no_active_miss': '全部搞定！ 没有待处理的任务。',
        'send_money': '汇款',
        'to_whom': '收款人',
        'how_much': '多少钱？',
        'send_now': '立即发送 💸',
        'insufficient': '余额不足。',
        'transfer_done': '转账成功完成！',
        'profile_tab': '头像',
        'theme_select': '🎨 界面主题',
        'theme_changed': '主题已更新！',
        'fx_title': '财富换算',
        'next_allowance': '下一次零花钱',
        'avatar_builder': '创建你的头像',
        'face': '脸型',
        'hair': '发型',
        'clothes': '衣服',
        'save_avatar': '保存头像',
        'bg_image_label': '背景图片 (上传)',
        'bg_image_placeholder': '上传图片...',
        'bg_updated': '背景已更新！',
        'remove_bg': '移除背景',
        'bg_removed': '背景已移除！',
    },
    'hi': {
        'bal': 'मेरा बैलेंस',
        'logout': 'लॉग आउट',
        'refresh': 'रिफ्रेश',
        'lang_sel': 'भाषा',
        'status': 'स्थिति',
        'value': 'राशि',
        'reason': 'कारण',
        'confirm': 'पुष्टि करें',
        'cancel': 'रद्द करें',
        'execute': 'निष्पादित करें',
        'loading': 'लोड हो रहा है...',
        'change_pass': '🔒 पासवर्ड बदलें',
        'password': 'पासवर्ड',
        'new_pass': '🔑 नया पासवर्ड',
        'pass_changed': 'पासवर्ड सफलतापूर्वक बदला गया!',
        'cmd_header': 'RIPARITECH कमांड',
        'family_bal': '💰 संपत्ति निगरानी',
        'panel': '🔎 कार्य',
        'cashier': '💸 प्रविष्टियाँ',
        'mgmt': '⚙️ उपयोगकर्ता',
        'allowance_tab': '📅 जेब खर्च',
        'tab_approvals': 'स्वीकृतियां',
        'tab_followup': 'फॉलो-अप',
        'tab_new_mission': 'नया मिशन',
        'validate_delivery': 'डिलीवरी मान्य करें',
        'audit_title': 'समय सीमा और स्थिति ऑडिट',
        'no_pending': 'अनुमोदन की प्रतीक्षा में कोई डिलीवरी नहीं।',
        'pay_btn': 'भुगतान करें',
        'reopen_btn': 'कार्य फिर से खोलें',
        'overdue_warn': '⚠️ विलंब का पता चला',
        'late_delivery_warn': '⌛ देर से डिलीवरी',
        'on_time': 'समय पर ✅',
        'apply_fine': 'जुर्माना लगाएँ',
        'conf_fine_btn': 'जुर्माना पुष्टि करें',
        'fine_applied_toast': 'वित्तीय दंड लागू!',
        'cancel_btn': '🚫 रद्द करें',
        'col_responsible': 'जिम्मेदार',
        'col_task': 'कार्य',
        'col_completion': 'समापन',
        'col_actions': 'क्रियाएँ',
        'status_open': 'खुला',
        'status_pending': 'लंबित',
        'status_paid': 'भुगतान किया',
        'status_canceled': 'रद्द',
        'status_failed': 'विफल',
        'btn_fine': '💸 जुर्माना',
        'allowance_title': 'जेब खर्च सेटअप',
        'day_of_month': 'भुगतान दिवस (1-28)',
        'allowance_desc': 'स्वचालित जेब खर्च',
        'frequency': 'आवृत्ति',
        'freq_monthly': 'मासिक',
        'freq_weekly': 'साप्ताहिक',
        'freq_daily': 'दैनिक',
        'day_of_week': 'सप्ताह का दिन',
        'weekdays': ['सोमवार', 'मंगलवार', 'बुधवार', 'गुरुवार', 'शुक्रवार', 'शनिवार', 'रविवार'],
        'manual_adjust': 'मैनुअल बैलेंस समायोजन',
        'target_acc': 'खाता चुनें',
        'op_type': 'ऑपरेशन प्रकार',
        'deposit': 'जमा',
        'withdraw': 'निकासी',
        'active_users': 'सक्रिय उपयोगकर्ता',
        'new_user': 'नया उपयोगकर्ता',
        'delete_acc': 'खाता हटाएं',
        'home': 'इतिहास',
        'missions': 'मिशन',
        'transfer': 'स्थानांतरण',
        'tools': 'विनिमय',
        'last_mov': 'हालिया लेनदेन',
        'no_mov': 'कोई लेनदेन नहीं मिला।',
        'active_missions': 'सक्रिय मिशन',
        'deadline': 'समय सीमा',
        'no_deadline': 'कोई समय सीमा निर्धारित नहीं',
        'mark_done': 'पूर्ण के रूप में चिह्नित करें',
        'sent_approval': 'मिशन अनुमोदन के लिए भेजा गया! 🚀',
        'no_active_miss': 'सब साफ़! कोई लंबित मिशन नहीं।',
        'send_money': 'पैसे भेजें',
        'to_whom': 'प्राप्तकर्ता',
        'how_much': 'कितना?',
        'send_now': 'अभी भेजें 💸',
        'insufficient': 'अपर्याप्त शेष राशि।',
        'transfer_done': 'स्थानांतरण सफलतापूर्वक पूरा हुआ!',
        'profile_tab': 'अवतार',
        'theme_select': '🎨 इंटरफ़ेस थीम',
        'theme_changed': 'थीम अपडेट की गई!',
        'fx_title': 'धन रूपांतरण',
        'next_allowance': 'अगला जेब खर्च',
        'avatar_builder': 'अपना अवतार बनाएं',
        'face': 'चेहरा',
        'hair': 'बाल',
        'clothes': 'कपड़े',
        'save_avatar': 'अवतार सहेजें',
        'bg_image_label': 'पृष्ठभूमि छवि (अपलोड)',
        'bg_image_placeholder': 'एक छवि अपलोड करें...',
        'bg_updated': 'पृष्ठभूमि अपडेट की गई!',
        'remove_bg': 'पृष्ठभूमि हटाएं',
        'bg_removed': 'पृष्ठभूमि हटा दी गई!',
    }
}

def t(key):
    lang = st.session_state.get('lang', 'pt')
    return TRANSLATIONS.get(lang, TRANSLATIONS['pt']).get(key, key)

@st.cache_data(ttl=600)
def get_balance(uid):
    res = run_query("SELECT SUM(amount) as total FROM transactions WHERE user_id=:uid", params={'uid': uid})
    val = res.iloc[0]['total'] if res is not None and not res.empty and pd.notnull(res.iloc[0]['total']) else 0.0
    return val

def get_family_balances():
    query = """
        SELECT u.id, u.name, u.avatar_config, COALESCE(SUM(t.amount), 0) as balance 
        FROM users u 
        LEFT JOIN transactions t ON u.id = t.user_id 
        WHERE u.role = 'user' 
        GROUP BY u.id, u.name, u.avatar_config ORDER BY u.name
    """
    return run_query(query)
