# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
from .database import run_query

# Dicionário de traduções v14.1 - SUPORTE TOTAL MULTI-IDIOMA
TRANSLATIONS = {
    'pt': {
        # Gerais
        'bal': 'Meu Saldo',
        'logout': 'Sair',
        'refresh': 'Atualizar',
        'lang_sel': 'Idioma',
        'status': 'Status',
        'value': 'Valor',
        'reason': 'Motivo',
        'confirm': 'Confirmar',
        'cancel': 'Cancelar',
        'execute': 'Executar',
        'loading': 'Carregando...',
        
        # Admin - Cabeçalhos
        'cmd_header': 'COMANDO RIPARITECH',
        'family_bal': '💰 Monitoramento de Ativos',
        'panel': '🔎 Tarefas',
        'cashier': '💸 Lançamentos',
        'mgmt': '⚙️ Usuários',
        
        # Admin - Tarefas
        'tab_approvals': 'Aprovações',
        'tab_followup': 'Acompanhar',
        'tab_new_mission': 'Nova Missão',
        'validate_delivery': 'Validar Entregas',
        'audit_title': 'Auditoria de Prazos e Status',
        'no_pending': 'Nenhuma entrega aguardando aprovação.',
        'pay_btn': 'Pagar',
        'reopen_btn': 'Reabrir Missão',
        'overdue_warn': '⚠️ ATRASO DETECTADO',
        'late_delivery_warn': '⌛ ENTREGUE COM ATRASO',
        'on_time': 'No prazo ✅',
        'apply_fine': 'Aplicar Multa',
        'conf_fine_btn': 'Confirmar Multa',
        'fine_applied_toast': 'Punição financeira aplicada!',
        'cancel_btn': '🚫 Cancelar',
        'col_responsible': 'Responsável',
        'col_task': 'Tarefa',
        'col_completion': 'Conclusão',
        'col_actions': 'Ações',
        'status_open': 'ABERTO',
        'status_pending': 'PENDENTE',
        'status_paid': 'PAGO',
        'status_canceled': 'CANCELADO',
        'status_failed': 'FALHOU',
        'btn_fine': '💸 Multar',
        
        # Admin - Lançamentos e Usuários
        'manual_adjust': 'Ajuste de Saldo Manual',
        'target_acc': 'Escolher Conta',
        'op_type': 'Tipo de Operação',
        'deposit': 'Depósito',
        'withdraw': 'Retirada',
        'active_users': 'Usuários Ativos',
        'new_user': 'Novo Usuário',
        'delete_acc': 'Excluir Conta',
        
        # Kids - Abas
        'home': 'Extrato e Histórico',
        'missions': 'Missões',
        'transfer': 'Transferir',
        'tools': 'Câmbio',
        
        # Kids - Funcionalidades
        'last_mov': 'Últimas Movimentações',
        'no_mov': 'Nenhum registro de movimentação encontrado.',
        'active_missions': 'Missões Ativas',
        'deadline': 'Prazo',
        'no_deadline': 'Sem prazo definido',
        'mark_done': 'MARCAR COMO CONCLUÍDO',
        'sent_approval': 'Missão enviada para aprovação do Comando! 🚀',
        'no_active_miss': 'Tudo pronto! Você não tem missões pendentes.',
        'send_money': 'Enviar Dinheiro',
        'to_whom': 'Destinatário',
        'how_much': 'Quanto?',
        'send_now': 'ENVIAR AGORA 💸',
        'insufficient': 'Saldo insuficiente.',
        'transfer_done': 'Transferência realizada com sucesso!',
        'fx_title': 'Conversão de Patrimônio',
    },
    'en': {
        'bal': 'My Balance',
        'logout': 'Logout',
        'refresh': 'Refresh',
        'lang_sel': 'Language',
        'status': 'Status',
        'value': 'Amount',
        'reason': 'Reason',
        'confirm': 'Confirm',
        'cancel': 'Cancel',
        'execute': 'Execute',
        'loading': 'Loading...',
        'cmd_header': 'RIPARITECH COMMAND',
        'family_bal': '💰 Asset Monitoring',
        'panel': '🔎 Tasks',
        'cashier': '💸 Entries',
        'mgmt': '⚙️ Users',
        'tab_approvals': 'Approvals',
        'tab_followup': 'Follow-up',
        'tab_new_mission': 'New Mission',
        'validate_delivery': 'Validate Deliveries',
        'audit_title': 'Deadline & Status Audit',
        'no_pending': 'No deliveries waiting for approval.',
        'pay_btn': 'Pay',
        'reopen_btn': 'Reopen Task',
        'overdue_warn': '⚠️ OVERDUE DETECTED',
        'late_delivery_warn': '⌛ LATE DELIVERY',
        'on_time': 'On time ✅',
        'apply_fine': 'Apply Fine',
        'conf_fine_btn': 'Confirm Fine',
        'fine_applied_toast': 'Financial penalty applied!',
        'cancel_btn': '🚫 Cancel',
        'col_responsible': 'Responsible',
        'col_task': 'Task',
        'col_completion': 'Completion',
        'col_actions': 'Actions',
        'status_open': 'OPEN',
        'status_pending': 'PENDING',
        'status_paid': 'PAID',
        'status_canceled': 'CANCELED',
        'status_failed': 'FAILED',
        'btn_fine': '💸 Fine',
        'manual_adjust': 'Manual Balance Adjustment',
        'target_acc': 'Select Account',
        'op_type': 'Operation Type',
        'deposit': 'Deposit',
        'withdraw': 'Withdrawal',
        'active_users': 'Active Users',
        'new_user': 'New User',
        'delete_acc': 'Delete Account',
        'home': 'History',
        'missions': 'Missions',
        'transfer': 'Transfer',
        'tools': 'Exchange',
        'last_mov': 'Recent Transactions',
        'no_mov': 'No transactions found.',
        'active_missions': 'Active Missions',
        'deadline': 'Deadline',
        'no_deadline': 'No deadline set',
        'mark_done': 'MARK AS DONE',
        'sent_approval': 'Mission sent for Command approval! 🚀',
        'no_active_miss': 'All clear! No pending missions.',
        'send_money': 'Send Money',
        'to_whom': 'Recipient',
        'how_much': 'Amount?',
        'send_now': 'SEND NOW 💸',
        'insufficient': 'Insufficient balance.',
        'transfer_done': 'Transfer completed successfully!',
        'fx_title': 'Wealth Conversion',
    },
    'es': {
        'bal': 'Mi Saldo',
        'logout': 'Salir',
        'refresh': 'Actualizar',
        'lang_sel': 'Idioma',
        'status': 'Estado',
        'value': 'Valor',
        'reason': 'Motivo',
        'confirm': 'Confirmar',
        'cancel': 'Cancelar',
        'execute': 'Ejecutar',
        'loading': 'Cargando...',
        'cmd_header': 'COMANDO RIPARITECH',
        'family_bal': '💰 Monitoreo de Activos',
        'panel': '🔎 Tareas',
        'cashier': '💸 Movimientos',
        'mgmt': '⚙️ Usuarios',
        'tab_approvals': 'Aprobaciones',
        'tab_followup': 'Seguimiento',
        'tab_new_mission': 'Nueva Misión',
        'validate_delivery': 'Validar Entregas',
        'audit_title': 'Auditoría de Plazos y Estado',
        'no_pending': 'No hay entregas pendientes.',
        'pay_btn': 'Pagar',
        'reopen_btn': 'Reabrir Tarea',
        'overdue_warn': '⚠️ ATRASO DETECTADO',
        'late_delivery_warn': '⌛ ENTREGADO CON ATRASO',
        'on_time': 'A tiempo ✅',
        'apply_fine': 'Aplicar Multa',
        'conf_fine_btn': 'Confirmar Multa',
        'fine_applied_toast': '¡Penalización aplicada!',
        'cancel_btn': '🚫 Cancelar',
        'col_responsible': 'Responsable',
        'col_task': 'Tarea',
        'col_completion': 'Conclusión',
        'col_actions': 'Acciones',
        'status_open': 'ABIERTO',
        'status_pending': 'PENDIENTE',
        'status_paid': 'PAGADO',
        'status_canceled': 'CANCELADO',
        'status_failed': 'FALLIDO',
        'btn_fine': '💸 Multar',
        'manual_adjust': 'Ajuste Manual de Saldo',
        'target_acc': 'Elegir Cuenta',
        'op_type': 'Tipo de Operación',
        'deposit': 'Depósito',
        'withdraw': 'Retiro',
        'active_users': 'Usuarios Activos',
        'new_user': 'Nuevo Usuario',
        'delete_acc': 'Eliminar Cuenta',
        'home': 'Historial',
        'missions': 'Misiones',
        'transfer': 'Transferir',
        'tools': 'Cambio',
        'last_mov': 'Últimos Movimientos',
        'no_mov': 'No se encontraron movimientos.',
        'active_missions': 'Misiones Activas',
        'deadline': 'Plazo',
        'no_deadline': 'Sin plazo definido',
        'mark_done': 'MARCAR COMO HECHO',
        'sent_approval': '¡Misión enviada para aprobación! 🚀',
        'no_active_miss': '¡Todo listo! No tienes misiones pendientes.',
        'send_money': 'Enviar Dinero',
        'to_whom': 'Destinatario',
        'how_much': '¿Cuánto?',
        'send_now': 'ENVIAR AHORA 💸',
        'insufficient': 'Saldo insuficiente.',
        'transfer_done': '¡Transferencia realizada!',
        'fx_title': 'Conversión de Patrimonio',
    }
}

def t(key):
    lang = st.session_state.get('lang', 'pt')
    return TRANSLATIONS.get(lang, TRANSLATIONS['pt']).get(key, key)

@st.cache_data(ttl=600)
def get_balance(uid):
    res = run_query("SELECT SUM(amount) as total FROM transactions WHERE user_id=:uid", params={'uid': uid})
    val = res.iloc[0]['total'] if res is not None and not res.empty and pd.notnull(res.iloc[0]['total']) else 0.0
    return val

def get_family_balances():
    query = """
        SELECT u.id, u.name, COALESCE(SUM(t.amount), 0) as balance 
        FROM users u 
        LEFT JOIN transactions t ON u.id = t.user_id 
        WHERE u.role = 'user' 
        GROUP BY u.name, u.id ORDER BY u.name
    """
    return run_query(query)
